name: kc_birds
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - librosa
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-lightning
  - scikit-learn
  - tqdm
  - click
  - jupyter
  - ipykernel
  - pip:
      - torchmetrics
      - seaborn
      - tensorboard
      - soundfile
      - soxr
      - python-dotenv